import type { WeaponStatsType } from "@/types/itemTypes";

export const WEAPON_STATS: Record<string, WeaponStatsType> = {
  'sword_0': {
    baseDmg: 3,
    dmgDice: 5,
    name: 'Short Sword',
    damageType: 'slash',
    quantityAllowed: 2,
    weight: '1H',
    itemClass: 'sword',
    itemType: 'weapon',
    rarity: 'common',
    bonusCritChance: 0.05,
  },
  'spear_0': {
    baseDmg: 2,
    dmgDice: 6,
    name: 'Short Spear',
    damageType: 'pierce',
    quantityAllowed: 1,
    weight: '1H',
    itemClass: 'spear',
    itemType: 'weapon',
    rarity: 'common',
    bonusCritChance: 0.05, 
    bonusRange: 1,
  },
  'mace_0': {
    baseDmg: 3,
    dmgDice: 5,
    name: 'Club',
    damageType: 'blunt',
    quantityAllowed: 2,
    weight: '1H',
    itemClass: 'mace',
    itemType: 'weapon',
    rarity: 'common',
    stunChance: 0.15,
  },
  'staff_0': {
    baseDmg: 0,
    dmgDice: 8,
    name: 'Short Staff',
    damageType: 'blunt',
    quantityAllowed: 1,
    weight: '2H',
    itemClass: 'staff',
    itemType: 'weapon',
    rarity: 'common',
    bonusCritChance: 0.05,
    bonusRange: 1,
  },
  'focus_0': {
    baseDmg: 0,
    dmgDice: 10,
    name: 'Wooden Wand',
    damageType: 'magic',
    quantityAllowed: 1,
    weight: '1H',
    itemClass: 'focus',
    itemType: 'weapon',
    rarity: 'common',
    bonusRange: 2,
  },
  'bow_0': {
    baseDmg: 2,
    dmgDice: 6,
    name: 'Short Bow',
    damageType: 'pierce',
    quantityAllowed: 1,
    weight: '2H',
    itemClass: 'bow',
    itemType: 'weapon',
    rarity: 'common',
    bonusRange: 4,
  },
  'dagger_0': {
    baseDmg: 2,
    dmgDice: 4,
    name: 'Shiv',
    damageType: 'slash',
    quantityAllowed: 2,
    weight: '1H',
    itemClass: 'dagger',
    itemType: 'weapon',
    rarity: 'common',
    bonusCritChance: 0.15,
  },
  't-knife_0': {
    baseDmg: -1,
    dmgDice: 6,
    name: 'Shiv',
    damageType: 'slash',
    quantityAllowed: 2,
    weight: '1H',
    itemClass: 'dagger',
    itemType: 'weapon',
    rarity: 'common',
    bonusCritChance: 0.1,
    bonusRange: 2
  },
  'longsword_0': {
    baseDmg: 2,
    dmgDice: 7,
    name: 'Long Sword',
    damageType: 'slash',
    quantityAllowed: 2,
    weight: '2H',
    itemClass: 'sword',
    itemType: 'weapon',
    rarity: 'common',
    bonusCritChance: 0.05,
  },
  'longaxe_0': {
    baseDmg: 1,
    dmgDice: 9,
    name: 'Long Sword',
    damageType: 'slash',
    quantityAllowed: 1,
    weight: '2H',
    itemClass: 'sword',
    itemType: 'weapon',
    rarity: 'common',
    bonusCritChance: 0.05,
    bleedChance: 0.05
  },
  'longmace_0': {
    baseDmg: 0,
    dmgDice: 10,
    name: 'Maul',
    damageType: 'blunt',
    quantityAllowed: 1,
    weight: '2H',
    itemClass: 'mace',
    itemType: 'weapon',
    rarity: 'common',
    stunChance: 0.2,
  },
  'crossbow_0': {
    baseDmg: 1,
    dmgDice: 5,
    name: 'Simple Crossbow',
    damageType: 'pierce',
    quantityAllowed: 1,
    weight: '2H',
    itemClass: 'crossbow',
    itemType: 'weapon',
    rarity: 'common',
    bonusRange: 3,
    bonusCritChance: 0.1
  },
}  